Question 1: Compute simple vector formula

In [28]:
import numpy as np
import math

In [29]:
# a) compute vector length (norm):
def compute_vector_length_ver0(vector):
    sum_to_power_of_2 = 0 
    for element in vector:
        sum_to_power_of_2 += element**2
    len_of_vector = math.sqrt(sum_to_power_of_2)
    return len_of_vector
    

def compute_vector_length_ver1(vector):
    #vector length = norm = sum of element^2 and squared root it
    norm = np.sqrt(np.sum([vec ** 2 for vec in vector]))

    return norm

def compute_vector_length_ver2(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

vector = np.array([-2, 4, 9, 21])
result_a = compute_vector_length_ver2(vector)
print(round(result_a, 2))

23.28


In [30]:
# b) dot product: 
def compute_dot_product_ver1(vector1, vector2):
    #ct 1: a x b = norm(a) x norm(b) x cos(ab)
    #ct 2: 
    dot_product_result = np.dot(vector1, vector2)
    return dot_product_result

vec1 = np.array([0, 1, -1, 2])
vec2 = np.array([2, 5, 1, 0])
result_b = compute_dot_product_ver1(vec1, vec2)
result_b = vec1.dot(vec2) #or vec2.dot(vec1) or vec1 @ vec2
print(result_b)

4


In [31]:
# c) multiply matrix with a vector (same like two vectors)
def multiply_vector_matrix(matA, vecB):
    result = compute_dot_product_ver1(matA, vecB)
    return result

#Checking dimension of shape with numpy
mat1 = np.array([[0, 1, -1, 2],
                 [0, 1, 2, 4]])
print(mat1.shape)
vec2 = np.array([2, 5, 1, 0])
print(vec2.shape)

multiply_vector_matrix(mat1, vec2)



(2, 4)
(4,)


array([4, 7])

In [32]:
# d) multiply matrix with matrix:
def multiply_matrix_with_matrix(matA, matB):
    result = np.dot(matA, matB)
    return result 

mat1 = np.array([[0, 1, -1, 2], 
                 [0, 1, -1, 2]])
print(mat1.shape)
mat2 = np.array([[0, 1], 
                 [0, 1],
                 [0, 1], 
                 [0, 1]])
print(mat2.shape)

# (2x4) x (4x2) = (2x2)
result_mat1_x_mat2 = multiply_matrix_with_matrix(mat1, mat2)
print(result_mat1_x_mat2)
print("\n-------------\n")
# (4x2) x (2x4) = (4x4)
result_mat2_x_mat1 = multiply_matrix_with_matrix(mat2, mat1)
print(result_mat2_x_mat1)


(2, 4)
(4, 2)
[[0 2]
 [0 2]]

-------------

[[ 0  1 -1  2]
 [ 0  1 -1  2]
 [ 0  1 -1  2]
 [ 0  1 -1  2]]


In [33]:
# e) inverse matrix:
def inverse_matrix_without_numpy(mat1):
    # Extract elements of the 2x2 matrix
    a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]
    
    # Calculate the determinant
    determinant = a * d - b * c
    
    # Ensure the matrix is invertible (determinant should not be zero)
    if determinant == 0:
        raise ValueError("The matrix is not invertible.")
    
    # Calculate the inverse using the formula
    inverse_matrix = [
        [d / determinant, -b / determinant],
        [-c / determinant, a / determinant]
    ]
    
    return inverse_matrix
    



def inverse_matrix(mat1):
    inverse_matrix = np.linalg.inv(mat1)
    return inverse_matrix

matrix = np.array([[0, 1], 
                 [9, 1],])
print(inverse_matrix(matrix))
print("\n------------\n")
print(inverse_matrix_without_numpy(matrix))

[[-0.11111111  0.11111111]
 [ 1.          0.        ]]

------------

[[-0.1111111111111111, 0.1111111111111111], [1.0, -0.0]]


Question 2: Calculating Eigenvalues Eigenvectors

In [34]:
#Hông Hiểu Cần Xem Lại
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues,eigenvectors


matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

Question 3: Computing the Cosine Similarity

In [36]:
def computing_cosine(vector1, vector2):
    a, b = compute_vector_length_ver2(vector1), compute_vector_length_ver2(vector2)
    cosine_result = compute_dot_product_ver1(vector1, vector2) / (a * b)

    return cosine_result

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])

print(computing_cosine(x, y))

0.5773502691896257


Question 4: Background subtraction (tách nền)

In [37]:
import numpy as np
import cv2